sudo: required
services:
  - docker

before_install:
  - docker build -t keyproco/sa9si-webapp -f Dockerfile.dev .
script:
  - docker run -e CI=true keyproco/sa9si-webapp  npm run test
deploy:
  provider: elasticbeanstalk
  edge: true
  region: "us-east-1"
  app: "sa9si-webapp"
  env: "Sa9siWebapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-690260229594"
  bucket_path: "sa9si-webapp"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
